[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "15.2.1"
  YARN_VERSION = "1.22.5"
  YARN_FLAGS = "--frozen-lockfile"
  BABEL_CACHE_FOLDER = "/opt/build/cache/"
  BUILD_REPORT_ERRORS_ONLY = "true"
